# Dataset
dataset: coco
data_path: coco
labeled_batch_size: 2
unlabeled_batch_size: 14
workers: 10
data_augmentation: hard

# Model
model: fasterrcnn_resnet50_fpn
use_score: True
sync_bn: True
finetune: False
eval_freq: 2000

# Optimizer
iterations: 180000
lr: 0.08
momentum: 0.9
weight_decay: 0.0001
lr_scheduler: multisteplr
lr_step: [120000, 160000]
lr_gamma: 0.1