# Dataset
dataset: dior
data_path: dior
batch_size: 8 # 16x4 gpus
workers: 5
data_augmentation: hard

# Model
model: fasterrcnn_resnet50_fpn
use_score: False
sync_bn: True
finetune: True
eval_freq: 1000

# Optimizer
iterations: 10000
lr: 0.0008
momentum: 0.9
weight_decay: 0.0001
lr_scheduler: multisteplr
lr_step: [6000]
lr_gamma: 0.1

