# Dataset
dataset: coco
data_path: coco
batch_size: 16 # 16x4 gpus
workers: 10
data_augmentation: hard
aspect_ratio_group_factor: 3

# Model
model: fasterrcnn_resnet50_fpn
use_score: False
sync_bn: True
finetune: True
eval_freq: 1000

# Optimizer
iterations: 10000
lr: 0.0008
momentum: 0.9
weight_decay: 0.0001
lr_scheduler: multisteplr
lr_step: [6000]
lr_gamma: 0.1

