# Dataset
dataset: dior
data_path: dior
batch_size: 8 # 16x4 gpus
workers: 5
data_augmentation: hard

# Model
model: fasterrcnn_resnet50_fpn
use_score: False
sync_bn: True
finetune: False
eval_freq: 2000

# Optimizer
iterations: 20000
lr: 0.08
momentum: 0.9
weight_decay: 0.0001
lr_scheduler: multisteplr
lr_step: [13333, 17777]
lr_gamma: 0.1

